

          -  Type 2 Diabetes Mellitus (T2DM) as per American Diabetes Association (ADA) guidelines

          -  Age >= 18

          -  Confirmed COVID-19

          -  Mild COVID-19 defined as any of the following: fever, malaise, cough, headache, sore
             throat, myalgia, nasal congestion, diarrhea

          -  Moderate COVID-19 is defined as > 2 of the following in non-intubated patients: any
             symptom of mild disease, radiographic imaging (chest x-ray or lung ultrasound) with
             bilateral ground glass opacities or bilateral consolidations, SpO2 <90% up to 5L Nasal
             Cannula (NC)

          -  No additional signs or symptoms of severe COVID-19.

        