

          -  Age greater than 18 years

          -  Positive SARS-CoV-2 testing or consistent clinical syndrome (based on clinical picture
             e.g. characteristic infiltrates on chest x-ray, laboratory findings, and with
             agreement by two physicians) in patients under investigation (PUIs).

          -  Onset of symptoms < 7 days from date of enrollment

          -  Oxygen saturation of >94% on room air with defined risk factors (Table 1) consistent
             with moderate disease OR oxygen saturation of < 94% on room air consistent with severe
             disease

          -  Ability and willingness to comply with study procedures

        