

          -  Male or female aged 18 - 89 years at time of enrollment

          -  Hospitalized (or documented plan to hospitalize if patient is in the emergency
             department) with symptoms suggestive of COVID-19

          -  Illness of any duration that meets each of the following:

               1. Evidence of pneumonia, including radiographic infiltrates by imaging (chest
                  x-ray, CT scan, etc.) or clinical assessment (rales/crackles on exam)

               2. Requires supportive care, including non-invasive supplemental oxygen

          -  Laboratory-confirmed SARS-CoV-2 infection as determined by PCR or other commercial or
             public health assay within 7 days of enrollment

          -  Understands and agrees to comply with planned study procedures

          -  Provides informed consent signed by study patient or legally acceptable representative

        