

          -  Willing and able to provide written informed consent, or with a legal representative
             who can provide informed consent, or enrolled under International Conference on
             Harmonization (ICH) E6(R2) 4.8.15 emergency use provisions as deemed necessary by the
             investigator (age >=18), or willing and able to provide assent (age >=12 to <18, where
             locally and nationally approved) prior to performing study procedures

          -  Aged >= 18 years (at all sites), or aged >= 12 and < 18 years of age weighing >= 40 kg
             (where permitted according to local law and approved nationally and by the relevant
             institutional review board [IRB] or independent ethics committee [IEC])

          -  Severe Acute Respiratory Syndrome Coronavirus (SARS-CoV)-2 infection confirmed by
             polymerase chain reaction (PCR) test <= 4 days before randomization

          -  Currently hospitalized

          -  Peripheral capillary oxygen saturation (SpO2) <= 94% or requiring supplemental oxygen
             at screening

        Key 