

          1. Age >=18 years.

          2. Healthcare worker based in a primary, secondary or tertiary healthcare setting with a
             high risk of developing COVID-19 due to their potential exposure to patients with
             SARS-CoV-2 infection.

          3. Must have a 'smart' mobile phone with access to the internet for data collection
             purposes.

          4. Participants will provide informed consent via an electronic consent process.

        