

          -  Confirmed COVID-19 positive test result

          -  Mild to moderate respiratory disease defined by oxygen requirement of at least 2 L/min
             to maintain oxygen saturation level >=92%.

          -  Systolic blood pressure >= 110 mmHg.

          -  Age >=18 years old.

          -  Access to an electronic device that is able to access DocuSign online and email for
             consenting.

          -  Able to read/write/speak English or Spanish fluently.

          -  Subjects must have the ability to understand the requirements of the study, provide
             informed consent, and provide authorization of use and disclosure of personal health
             information.

          -  Negative pregnancy test for women of childbearing potential.

        