

          -  Hospitalization for management of SARS CoV-2 infection

          -  Positive SARS CoV-2 test

          -  Age >=18 years

          -  Provision of informed consent

          -  Electrocardiogram (ECG) <=48 hours prior to enrollment

          -  Complete blood count, glucose-6 phosphate-dehydrogenase (G6PD), comprehensive
             metabolic panel and magnesium <=48 hours prior to enrollment from standard of care.

          -  If participating in sexual activity that could lead to pregnancy, individuals of
             reproductive potential who can become pregnant must agree to use contraception
             throughout the study. At least one of the following must be used throughout the study:

               -  Condom (male or female) with or without spermicide

               -  Diaphragm or cervical cap with spermicide

               -  Intrauterine device (IUD)

               -  Hormone-based contraceptive

        