

          1. Participant is willing and able to provide informed consent.

          2. Participant is 18-75 years of age.

          3. Participant does not have symptoms of respiratory infection, including cough, fevers
             (temperature >38.0C), difficulty breathing, shortness of breath, chest pains, malaise,
             myalgia, headaches, nausea or vomiting, or other symptoms associated with COVID-19.

          4. Participant is willing to provide blood samples for the study.

          5. Subject agrees to all aspects of the study.

          6. The participant has no known allergies or contraindications (as stated in the consent
             form) to the use of hydroxychloroquine (HCQ) as noted in the 