

        Patients who meet all of the following criteria will be eligible to participate in the
        study:

          1. Must have provided informed consent in a manner approved by the Investigator's
             Institutional Review Board (IRB) or Independent Ethics Committee (IEC) prior to any
             assessments. If a patient is unable to provide informed consent due to their medical
             condition, the patient's legally authorized representative may consent on behalf of
             the study patient, as permitted by local law and institutional Standard Operating
             Procedures;

          2. Age > 18 and < 80 years old

          3. Male or female gender

          4. Confirmed SARS-CoV-2 infection by NP swab PCR

          5. Admitted to non-ICU level care at MGH

          6. WITH evidence of severe COVID-19 (at least 1 of the following):

               1. Fever > 38C

               2. Bilateral pulmonary infiltrates on chest X ray

               3. Need for supplemental O2 to maintain saturation > 92%

          7. AND at least 1 of the following:

               1. Ferritin > 500 ng/ml

               2. CRP > 50 mg/L

          8. Women of childbearing potential (ie, not post-menopausal or surgically sterilized)
             must have a negative highly sensitive urine or serum pregnancy test before
             randomization. Participating women of childbearing potential must be willing to
             consistently use effective methods of contraception (ie, condom, combined oral
             contraceptive, implant, injectable, indwelling intrauterine device, or a vasectomized
             partner) from screening until at least 90 days after administration of the last dose
             of study drug;

          9. The patient must be willing and able to provide informed consent and abide all study
             requirements and restrictions.

        