

        In order to be eligible to participate in this study, an individual must meet all of the
        following criteria:

          1. >18 years of age

          2. Hospitalized patient with a diagnosis of COVID-19

          3. Consistent with the institution guidelines, D-dimer > 500ng/ml

               1. If a D-Dimer is between 500ng/ml to 2,000ng/ml - there appears to be clinical
                  equipoise by the NYU medical community

               2. If a D-Dimer is >2,000 and < 10,000 and is not on a higher dose anticoagulation
                  and a blood clot is not suspected and there is clinical equipoise, a patient may
                  be approached for enrollment

        