

          1. Should be at least 18 years of age,

          2. Male or female,

          3. Diagnosed with COVID-19 and confirmed SARS-coV-2 viral infection.

          4. Able to sign the consent form.

          5. Severe COVID-19 (Appendix A), or NIAID 8-point ordinal score 3 to 4 (requiring
             non-invasive ventilation or oxygen, a SpO2 </= 94% or tachypnea (respiratory rate >/=
             24 breaths/min), Appendix B).

        