

          -  Evidence of a positive SARS-CoV-2 test and test results received within the previous
             three days

          -  Not currently hospitalized

          -  Willing and able to receive study drug by mail

          -  Willing and able to return the internet-based study questionnaires at baseline, day 3,
             7, 14, 21 days

          -  No known allergy or other contraindication to macrolides

          -  Age 18 years or older at the time of enrollment

          -  No known history of prolongation of the QT interval (eg. History of torsades de
             pointes, congenital long QT syndrome, bradyarrhthmia)

          -  No recent use of hydroxychloroquine within the past 7 days for participants >55 years
             of age

          -  Provision of informed consent
      