

          1. Admitted to a hospital with symptoms suggestive of COVID-19 infection.

          2. Subject (or legally authorized representative) provides informed consent prior to
             initiation of any study procedures.

          3. Subject (or legally authorized representative) understands and agrees to comply with
             planned study procedures.

          4. Male or non-pregnant female adult > / = 18 years of age at time of enrollment.

          5. Has laboratory-confirmed SARS-CoV-2 infection as determined by polymerase chain
             reaction (PCR) or other commercial or public health assay in any specimen, as
             documented by either or the following:

               -  PCR positive in sample collected < 72 hours prior to randomization; OR

               -  PCR positive in sample collected >/= 72 hours prior to randomization, documented
                  inability to obtain a repeat sample (e.g. due to lack of testing supplies,
                  limited testing capacity, results taking >24 hours, etc.) AND progressive disease
                  suggestive of ongoing SARS-CoV-2 infection.

          6. Illness of any duration, and at least one of the following:

               -  Radiographic infiltrates by imaging (chest x-ray, CT scan, etc.), OR

               -  SpO2 < / = 94% on room air, OR

               -  Requiring supplemental oxygen, OR

               -  Requiring mechanical ventilation.

          7. Women of childbearing potential must agree to either abstinence or use at least one
             primary form of contraception not including hormonal contraception from the time of
             screening through Day 29.

          8. Agrees to not participate in another clinical trial for the treatment of COVID-19 or
             SARS-CoV-2 through Day 29.

        