

          1. Written informed consent must be obtained from the subject in accordance with
             requirements of the study center's institutional review board (IRB) or Subjects must
             provide w informed consent in accordance with requirements of the study center's IRB
             or ethics committee, prior to the initiation of any protocol-required procedures

          2. Subjects must agree to provide all requested demographic information (i.e. gender,
             race)

          3. Subjects must be able to read and understand English or Spanish

          4. Subjects must be over the age of 18 years

          5. Subjects must have laboratory-confirmed SARS-CoV-2 infection as determined by
             PCR-based commercial or public health assay

          6. Subjects must have symptoms that require hospitalization with supplemental oxygen as
             determined by the admitting physician. The maximum nasal cannula O2 concentration
             should be determined by the treating clinician and the limitations of the specific
             equipment

          7. Subjects must be willing and able to comply with study-related procedures/assessments

        