

          1. Ability to understand and the willingness to sign a written informed consent document.

          2. Individuals aged >= 18 years of all races and ethnic groups.

          3. Must have documented positive test result for SARS-CoV-2 (COVID19), or high clinical
             suspicion for SARS-CoV-2 based on presence of typical clinical findings (e.g., fever,
             respiratory symptoms, pulmonary abnormalities on chest X-ray or CT scan), lack of
             alternative diagnosis, and history of exposure to a known case of SARS-CoV-2 infection
             within the past 14 days

          4. Not receiving institutional therapy for treatment of SARS-CoV-2, including (but not
             limited to) remdesivir, chloroquine, hydroxychloroquine, or any other investigational
             agent(s).

          5. Must meet at least one of the following clinical stratifications:

               1. Have at least 1 minor criterion per ATS criteria (refer to Appendix A), or

               2. Have fever, respiratory symptoms, with pneumonia visible on chest imaging (e.g.,
                  X-ray or computed tomography [CT]), or

               3. High risk for poor outcome, as defined by any one of the following:

             i. Age >= 60 years old

             ii. Underlying medical comorbidities, defined as:

               -  Cardiovascular disease

               -  Diabetes

               -  Chronic respiratory disease (e.g., COPD)

               -  Hypertension, defined as blood pressure >= 140 / 90 mmHg

             iii. Solid organ or stem cell transplant recipient

             iv. Diagnosis of solid or hematologic malignancy being treated with systemic
             chemotherapy

             v. Receipt of biologic agent or prednisone > 0.5 mg/kg/day (or equivalent)

          6. Participants with preexisting auditory damage are allowed.

          7. Participants with a history of epilepsy are allowed.

          8. Female participants of childbearing potential (FOCBP) must have a negative serum or
             urine pregnancy test (per institutional standards) prior to the start of study drug.

          9. FOCBP must agree to use highly-effective method(s) of contraception during the study
             and for 1 months after the last dose of study drug. FOCBP are those who have not been
             surgically sterilized or have not been free from menses for >1 year without an
             alternative medical cause.

         10. Male participants must agree to use an adequate method of contraception starting with
             the first dose of study therapy through at least 1 months after the last dose of study
             drug.

         11. Participant must agree to not breastfeed during the study or for 30 days after the
             last dose of study treatment.

        