

          -  Willing and able to provide written informed consent prior to performing study
             procedures (participants >= 18 years of age) or assent (participants >= 12 and < 18
             years of age) prior to performing study procedures. For participants >= 12 and < 18
             years of age, a parent or legal guardian willing and able to provide written informed
             consent prior to performing study procedures

          -  Severe Acute Respiratory Syndrome Coronavirus (SARS-CoV)-2 infection confirmed by
             polymerase chain reaction (PCR) test <= 4 days before randomization

          -  Currently hospitalized and requiring medical care for COVID-19

          -  Peripheral capillary oxygen saturation (SpO2) > 94% on room air at screening

          -  Radiographic evidence of pulmonary infiltrates

        Key 