

          1. Provision of informed consent

          2. Male or female patients aged >=18 years

          3. Currently hospitalized

          4. Confirmed SARS-CoV-2 infection by laboratory testing <72h prior to randomization or
             strongly suspected on presentation

          5. Chest radiography or CT findings consistent with COVID-19

          6. Mild-moderate disease: SpO2>=94% with low-flow supplemental oxygen (3 liters or less)

          7. Medical history of at least one of the following:

               1. hypertension

               2. T2DM

               3. atherosclerotic cardiovascular disease

               4. heart failure (with either reduced or preserved LVEF)

               5. CKD stage 3 to 4 (eGFR between 25 to 60 mL/min/1.73 m2)

        Key 