

          -  Men or women 18 to 80 years of age, inclusive, at the time of signing the informed
             consent

          -  Willing and able to provide informed consent

          -  Laboratory confirmed SARS-CoV-2 infection, with test results within past 72 hours

          -  Access to device and internet for Telehealth visits

          -  At increased risk of developing severe COVID-19 disease (at least one of the
             following)

               1. Age >=60 years

               2. Presence of pulmonary disease, specifically moderate or severe persistent asthma,
                  chronic obstructive pulmonary disease, pulmonary hypertension, emphysema

               3. Diabetes mellitus (type 1 or type 2), requiring oral medication or insulin for
                  treatment

               4. Hypertension, requiring at least 1 oral medication for treatment

               5. Immunocompromised status due to disease (e.g., those living with human
                  immunodeficiency virus with a CD4 T-cell count of <200/mm3)

               6. Immunocompromised status due to medication (e.g., persons taking 20 mg or more of
                  prednisone equivalents a day, anti-inflammatory monoclonal antibody therapies, or
                  cancer therapies)

               7. Body mass index >=30 (self-reported)

        