

          1. Health care worker (HCW) at the hospital who work on a "full time" basis during the
             study period. For the purposes of the study, "health care workers" are physicians,
             nurses, nurse practitioners, physician assistants, respiratory therapists, X-ray
             technicians, social workers and support staff (including but not limited to
             house-keeping, and porters).

          2. Age >=18 years.

          3. Ability to communicate with study staff in English

        