

          1. Patients included in the CORIMUNO-19 cohort

          2. Patients belonging to one of the 2 following groups:

               -  Group 1: patients not requiring ICU at admission with moderate and severe
                  pneumopathy according to the OMS Criteria of severity of COVID pneumopathy.

        Moderate cases :

        Cases meeting all of the following criteria:

          -  Showing fever and respiratory symptoms with radiological findings of pneumonia.

          -  Requiring between 3L/min and 5L/min of oxygen to maintain SpO2 >97% Severe cases

        Cases meeting any of the following criteria:

          -  Respiratory distress (30 breaths/ min);

          -  Oxygen saturation<=93% at rest in ambient air; or Oxygen saturation <=97 % with O2 >
             5L/min.

          -  PaO2/FiO2300mmHg

          -  Group 2: patients requiring ICU based on Criteria of severity of COVID pneumopathy.

          -  Respiratory failure and requiring mechanical ventilation

          -  No do-not-resuscitate order (DNR order)

        