

        I (first step):

          -  Admission to hospital

          -  Male or non-pregnant female, >=60 years of age or >=30 years of age plus one or more
             known risk factors (arterial hypertension, diabetes mellitus, coronary heart disease,
             heart failure, pre-existing chronic pulmonary disease)

          -  Confirmed SARS-CoV infection

          -  Radiographic evidence compatible with Covid-19 pneumonia (X-ray/CT scan, etc.)

          -  Signed Informed Consent Form

        II (second step; indication for intervention):

          -  CRP >=50mg/L plus 3 out of the following 5 criteria need to be fulfilled:

          -  Respiration Rate >=25

          -  SpO2 <93% (on ambient air)

          -  PaO2 <65 mmHg

          -  Persistent or increasing dyspnoea as defined by a one point increase on the mMRC
             dyspnoea scale (over 1 hour)

          -  Persistent or increasing oxygen demand (over 1 hour)

        