

          1. Agrees to the collection of oropharyngeal or anal swabs and venous blood per protocol.

          2. Male or non-pregnant female adult >=18 years of age at time of enrollment.

          3. Has laboratory-confirmed novel coronavirus infection as determined by polymerase chain
             reaction (PCR), or other commercial or public health assay in oropharyngeal or anal
             specimen within 72 hours prior to hospitalization.

          4. Illness of any duration, and at least one of the following:

               1. Radiographic infiltrates by imaging (chest x-ray, CT scan, etc.), OR

               2. Clinical assessment (evidence of rales/crackles on physical examination) AND SpO2
                  <=93% on room air, OR

               3. Requiring mechanical ventilation and/or supplemental oxygen, OR

               4. Sustained fever in the past 24 hours and unresponsive to NSAID or steroid

          5. Serum IL-6 >=3 times the upper limit of normal

        