

          1. Adult male and female healthcare workers >= 18 to <= 75 years of age upon study consent

          2. Healthcare workers with

              One day or more of exposure to suspect and/or positive COVID-19 patients, including
             but not limited to those working in the Emergency Department or Intensive Care Unit.

             OR

              Unprotected exposure to a known positive COVID-19 patient within 72 hours of
             screening.

          3. Afebrile with no constitutional symptoms

          4. Willing and able to comply with scheduled visits, treatment plan, and other study
             procedures

          5. Evidence of a personally signed and dated informed consent document indicating that
             the subject (or a legally acceptable representative) has been informed of all
             pertinent aspects of the study prior to initiation of any subject-mandated procedures

        