

          1. Age >=18 years at time of signing Informed Consent Form.

          2. Laboratory (RT-PCR) confirmed infection with CoVID-19.

          3. Hospitalised with Fever(>=36.7*C -axilla or oral temperature >= 38.0 *C or >=38.6*C
             tympanic or rectal) and cough;

          4. No difficulty swallowing oral medications.

          5. Must agree not to enroll in another study of an investigational agent prior to
             completion of Day 28 of study.

        