

          -  Aged between 18 and 80 years (Including 18and 80years, male or female).

          -  One of them:

               1. Laboratory (RT-PCR) and clinical symptoms confirmed case of novel coronavirus
                  pneumonia (COVID-19).

               2. Patients diagnosed clinically as suspected cases.

          -  Ability to communicate well with researchers and sign the informed consent Form (ICF)
             voluntarily.

        