

          1. Sign the informed consent form;

          2. Age >=18 years, regardless of gender;

          3. Subjects with pneumonia diagnosed as 2019-nCoV infection; A) Detection of 2019-nCoV
             nucleic acid positive by RT-PCR in respiratory tract or blood samples.

             B) The virus gene sequence of respiratory tract or blood samples is highly homologous
             to the known 2019-nCoV.

          4. According to the standard of "pneumonia diagnosis and treatment Program of New
             Coronavirus infection (trial Fifth Edition)" issued by National Health Commission of
             the People's Republic of China, clinical classification: mild, ordinary subjects; A)
             Mild type, the clinical symptoms were mild and no pneumonia was found in imaging.

        B) Common type, With fever, respiratory tract and other symptoms, the manifestations of
        pneumonia can be seen on imaging.

        