

          -  Written informed consent.

          -  Has been previously diagnosed with NTM, Burkholderia spp and Aspergillus spp. or
             Corona-like viral infection:

               1. NTM, Burkholderia spp and Aspergillus spp defined as positive culture(s) of at
                  least one species of Mycobacterium avium Complex (MAC) or Mycobacterium abscessus
                  Complex (MABSCor Burkholderia spp and Aspergillus spp) or Corona-like viral
                  infection:

               2. History of repeatedly positive cultures (2 or more), irregardless of therapy

          -  Male or female >=14 years of age.

          -  Female not pregnant at time of study.

          -  Has an FEV1 >= 30 % of predicted. c. Suspected corona-like viral infection

          -  Oxygen saturation on room air >92% at screening.

             a. Able to breathe without supplemental oxygen for 60 minutes

          -  Non-smoker for at least 6 months prior to screening and agrees not to smoke during the
             study.

          -  Willing and able to comply with the treatment schedule and procedures.

        