

          -  Age >18 years admitted to the University of Kansas Health System.

          -  Confirmation of infection with SARS-CoV-2 by PCR testing.

          -  Hypoxic respiratory failure

             o Requiring mechanical ventilation or oxygen, an oxygen saturation (SpO2) <=94% or a
             PaO2/FiO2 (P/F) ratio <300 or tachypnea (respiratory rate >=24 breaths/min).

          -  Other concomitant medications such as antivirals and hydroxychloroquine are allowed.

        