

          1. Volunteers who have understood and signed the informed consent;

          2. Age >=18 years, gender unlimited;

          3. Patients diagnosed with acute severe 2019-nCoV pneumonia:

               1. Laboratory (RT-PCR) confirmed infection with 2019-nCoV.

               2. Lung involvement confirmed with pulmonary CT scan.

               3. At least one of the following conditions should be met: respiratory distress, RR
                  >= 30 times/min; oxygen saturation <= 93% in resting state; PaO2/FiO2 <= 300mmHg;
                  respiratory failure and mechanical ventilation are required; shock occurs; ICU
                  monitoring and treatment is required in combination with other organ failure.

        