

          1. Admitted to participating hospital with symptoms suggestive of COVID-19 infection OR
             develop symptoms of COVID-19 during hospitalization

          2. Subject (or legally authorized representative) can provide written informed consent
             (in English or Spanish) affirming intention to comply with planned study procedures
             prior to enrollment

          3. Male or female adult aged 12 years or older at the time of enrollment

          4. Has laboratory-confirmed SARS-CoV-2 infection determined by a validated nucleic acid
             amplification assay (public health or commercial) in any respiratory specimen
             collected within 14 days of randomization

          5. Illness of any duration that includes

               -  Radiographic evidence of pulmonary infiltrates (chest X-ray or CT scan) OR

               -  Clinical documentation of lower respiratory symptoms (cough, shortness of breath,
                  wheezing) OR

               -  Any documented SpO2 <= 94% on room air OR

               -  Any inpatient initiation or supplemental oxygen regardless of documented cause

        