

          1. Voluntarily participating in the clinical study; fully understanding and being fully
             informed of the study and having signed the Informed Consent Form (ICF); willingness
             and capability to complete all the study procedures;

          2. Age 18-75 years (inclusive) at the time of signing ICF;

          3. Being confirmed with COVID-19-Moderate type according to Competent Authority and
             Italian Ministry of Health guidelines and to the recommendations reported in Appendix
             1 to the present protocol. Based on comprehensive analysis and judgement taking into
             account both the epidemiological history and clinical manifestations, the diagnosis is
             to be confirmed for suspected cases/clinically diagnosed cases with all of the
             following etiological evidences:

               -  Positivity in RT-PCR 2019-nCov test on respiratory tract specimens;

               -  High homology with known gene sequence of 2019-nCov in viral gene sequencing on
                  respiratory tract specimens; Note: The above criterion would be subject to any
                  update of the Competent Authority and Italian Ministry of Health guidelines and
                  to the recommendations reported in Appendix 1 to the present protocol. In case
                  any new etiologically detection methods/criteria or any new detectable specimens
                  become available after confirmed diagnosis, the new methods or new specimens may
                  or may not be used at the discretion of the investigator.

             Note: Sputum specimen is preferred for RT-PCR test of 2019-nCov nucleic acid; the
             specific type of respiratory tract specimen (e.g., nasopharyngeal swabs, sputum, lower
             respiratory tract secretions) is to be selected based on the conditions of the local
             laboratory.

             The type of specimen and detection method for 2019-nCov should remain consistent for
             the same subject receiving study treatment.

          4. Chest imaging (CT as first option or X-ray if CT not possible)-documented pneumonia;
             if CT cannot be performed, Pneumonia confirmed by X-ray may be used. The method of
             chest imaging pneumonia diagnosis must be consistent all through the study period.

          5. Patients with pyrexia (axillary >=37*C or oral >=37.5*C, or axillary or rectal>=38*C) or
             either respiratory rate >24/min and <30/min or cough; For not hospitalized patients,
             the Investigator should maintain the detection method consistent all through the study
             period. In addition, the Investigator should maintain the data collection and quality
             compliant with GCP requirements.

          6. The interval between symptoms onset and randomization is no more than 10 days;
             symptoms onset is primarily based on pyrexia, and can be based on cough or other
             related symptoms for patients without experiencing pyrexia following onset;

          7. For female subjects: evidence of post-menopause, or, for pre-menopause subjects,
             negative pre-treatment serum or urine pregnancy test. Menopause is defined as
             amenorrhea for at least 12 months without other medical cause, with the following
             age-specific requirements:

               -  For female subjects aged <50 years: menopause for at least 12 months following
                  withdrawal of exogenous hormonal therapy, with LH or FSH within the
                  post-menopausal ranges, or having undergone any contraceptive surgery (bilateral
                  oophorectomy or hysterectomy);

               -  For female subjects aged >=50 years: menopause for at least 12 months following
                  withdrawal of exogenous hormonal therapy, or having undergone
                  radiotherapy-induced oophorectomy with amenorrhea>1 year, or having undergone
                  chemotherapy-induced menopause with amenorrhea>1 year, or having undergone any
                  contraceptive surgery (bilateral oophorectomy or hysterectomy).

          8. Eligible subjects of child-bearing age (male or female) must agree to take effective
             contraceptive measures (including hormonal contraception, barrier methods or
             abstinence) with his/her partner during the study period and for at least 7 days
             following the last study treatment;

          9. Not participating in any other interventional drug clinical studies before completion
             of the present study.

        