of Cohort 1 #4 is adapted from the Flu guideline in China (2018) and
        community acquired pneumonia (CAP) guideline in China (2016)

        Cohort 1:

        Subjects must meet all of the following inclusion criteria at the time of randomization to
        be eligible for participation in this study:

          1. Males and Females >=18 years old

          2. Diagnosed as influenza (IFV) infection within 3 days before randomization

          3. Requires, at the time of randomization, supplemental oxygen >=2 LPM due to hypoxemia

          4. Subjects are severely ill

          5. In the opinion of investigator, subjects will be hospitalized at least 1 week.

          6. If female, subject must not be pregnant or nursing

        Cohort 2:

        Subjects must meet all of the following inclusion criteria at the time of randomization to
        be eligible for participation in this study:

          1. Males and Females >=18 years old

          2. Hypoxemia

          3. Subjects fulfill one of the following conditions:

               1. IFV subjects who are eligible for all inclusion criteria of Cohort 1 except for
                  acute hypoxemia at enrollment.

               2. Subjects confirmed with non-IFV SAD viral infection.

          4. Same in inclusion criteria #5 to #8 in Cohort 1.

        