

          -  Age >= 18 years old.

          -  Chronically treated with RAS blockers (ACE inhibitors or ARBs on the last prescription
             prior to admission with a treatment duration >= 1 month).

          -  Diagnosis of COVID-19 confirmed by the presence of SARS-CoV-2 on any biological sample
             with any detection method.

          -  Patients hospitalized in a non-intensive care unit.

          -  Pregnancy test at inclusion visit for women of childbearing potential.

          -  Women of childbearing potential must agree to use adequate contraception according to
             recommendations related to contraception and pregnancy testing in clinical trials, by
             Clinical Trial Facilitation Group (CTFG).

        