

          -  Adults >= 18 years of age

          -  Approval from the patient's primary service

          -  Admitted as an inpatient to University of Chicago Medicine

          -  Fever, documented in electronic medical record and defined as: T >= 38*C by any
             conventional clinical method (forehead, tympanic, oral, axillary, rectal)

          -  Positive test for active SARS-CoV-2 infection

          -  Radiographic evidence of infiltrates on chest radiograph (CXR) or computed tomography
             (CT)

        