

        Recent ( >= 6 days of flu-like symptoms or malaise yet <=14 days of flu-like symptoms or
        malaise prior to randomization) infection with COVID-19, confirmed by PCR within this
        period

          -  Presence of hypoxia defined as PaO2/FiO2 below 350 while breathing room air in upright
             position or PaO2/FiO2 below 280 on supplemental oxygen and immediately requiring high
             flow oxygen device or mechanical ventilation

          -  signs of cytokine release syndrome defined as ANY of the following:

               1. serum ferritin concentration >1000 mcg/L and rising since last 24h

               2. single ferritin above 2000 mcg/L in patients requiring immediate high flow oxygen
                  device or mechanical ventilation

               3. lymphopenia defined as <800 lymphocytes/microliter) and two of the following
                  extra criteria

                    -  Ferritin > 700 mcg/L and rising since last 24h

                    -  increased LDH (above 300 IU/L) and rising last 24h

                    -  D-Dimers > 1000 ng/mL and rising since last 24h

                    -  CRP above 70mg/L and rising since last 24h and absence of bacterial
                       infection

                    -  if three of the above are present at admission, no need to document 24h rise

          -  Chest X-ray or CT scan showing bilateral infiltrates within last 2 days

          -  Admitted to specialized COVID-19 ward or an ICU ward taking care of COVID-19 patients

          -  Age >= 18yrs, for patients above 70 years old, a frailty scale <= 2 is required

          -  Male or Female

          -  Willing and able to provide informed consent or legal representative willing to
             provide informed consent

        