

          -  DoD-affiliated personnel as defined in DoDI 6200.02, which includes
             emergency-essential civilian employees and/or contractor personnel accompanying the
             Armed Forces who are subject to the same health risk as military personnel

          -  Have a laboratory-confirmed COVID-19 diagnosis with moderate to severe disease
             presentation as determined by the principal investigator

          -  Patient or legally authorized representative (LAR) provides written informed consent,
             except as noted in 21 CFR 50.23

          -  Understands and agrees to comply with planned study procedures

          -  Available for clinical follow-up for duration of the treatment and follow-up period

          -  Woman of childbearing potential must

               -  Have a negative pregnancy test within 24 hours before starting treatment

               -  Agree not to become pregnant during treatment and for 1 months after receiving
                  remdesivir (Treatment will be a maximum of 10 doses given over a 10-day interval)

               -  Use at least 2 reliable forms of effective contraception, including 1 barrier
                  method, during treatment and for 1 month after the treatment period

        