

          1. Age:18~55 years old, unlimited gender.

          2. Laboratory (RT-PCR) confirmed infection with 2019-nCoV and accompanied with clinical
             manifestations.

          3. Patients with newly diagnosed respiratory discomfort who have been hospitalized (The
             proper diagnosis time is less than 7 days).

          4. Women who have no planned pregnancy in the next six months,and are willing to take
             effective measures to prevent contraception from the first dose of study drug to 30
             days after the last dose.

          5. Agree not to participate in other clinical studies within 30 days from the first dose
             of the study drug to the last dose.

          6. Patients who voluntarily sign informed consent forms.

        