

          1. COVID-19 has been diagnosed, and the nucleic acid test of respiratory specimens such
             as sputum or nasopharyngeal swabs has been negative for two consecutive times after
             treatment (sampling time interval of at least 24 hours);

          2. The nucleic acid test of specimens such as sputum, throat swabs, blood, feces and
             other specimens was positive for COVID-19 during screening visits;

          3. Voluntarily participate in research and sign informed consent.

        