

          1. Any gender

          2. No age limit

          3. Informed consent for participation in the study (consent can be oral if a written
             consent cannot be expressed. If the subject is incapable of giving an informed consent
             and an authorized representative is not available without a delay that would, in the
             opinion of the Investigator, compromise the potential life-saving effect of the
             treatment this can be administered without consent. Consent to remain in the research
             should be sought as soon the conditions of the patient will allow it)

          4. Virological diagnosis of SARS-CoV-2 infection (real-time PCR)

          5. Hospitalized due to clinical/instrumental diagnosis of pneumonia

          6. Oxygen saturation at rest in ambient air <=93% or requiring oxygen therapy or
             mechanical ventilation either non invasive or invasive (intubated)

          7. Patients with criteria #4 and #5 who have been already treated with tocilizumab before
             registration are eligible for the observational retrospective cohort

        