

          -  1. Aged between 18 and 75 years, extremes included, male or female

          -  2. Laboratory (RT-PCR) and clinical symptoms confirmed case of 2019-nCoV pneumonia,
             according to the official guideline "Pneumonia Diagnosis and Treatment Scheme for
             Novel Coronavirus Infection (Trial Version 5)"

          -  3. Hospitalised with a new onset respiratory illness (<=7 days since illness onset)

          -  4. No family planning within six months, and agree to take effective contraceptive
             measures throughout the study and for at least 30 days after the final study drug dose

          -  5. Must agree not to enroll in another study of an investigational agent prior to
             completion of Day 30 of study

          -  6. Informed Consent Form (ICF) signed voluntarily

        