

          1. Signed informed consent form (ICF) prior to participation in any study-related
             activities.

          2. Male or nonpregnant female patients >= 18 years at the time of signing ICF.

          3. Laboratory confirmed COVID-19 infection defined with a positive reverse
             transcription-polymerase chain reaction (RT-PCR) from any specimen and/or detection of
             SARS-CoV-2 immunoglobulin (Ig)M/IgG antibodies.

          4. Diagnostic confirmation of pneumonia by either chest X-ray or thoracic CT scan
             (preferable).

          5. Patient with severe acute respiratory syndrome related to COVID-19 under treatment as
             per hospital protocol during at least 48 hours.

          6. Patients with Sequential Organ Failure Assessment (SOFA) score <= 3 at the time of
             signing ICF.

          7. Patients hospitalized with fever defined as temperature >= 37,5 *C armpit.

          8. Patients with total lymphocyte count <=0,8 x106/mL.

          9. Patients who are showing SpO2 <= 92% on room air and/or patient who are showing SpO2 <=
             94% on room air and meet at least one of the following parameters:

               -  No objective clinical improvement at physician's discretion after 48 hours of
                  front-line standard care for COVID-19;

               -  Decrease in lymphocyte count (any decrease within 48 hours);

               -  Increase in ferritin levels (any increase within 48 hours);

               -  Increase in IL-6 levels (any increase within 48 hours);

               -  Increase in D-dimer levels (any increase within 48 hours);

               -  Increase in CRP levels (any increase within 48 hours);

               -  Increase in LDH levels (any increase within 48 hours);

               -  Increase in ESR levels (any increase within 48 hours).

         10. Life expectancy greater than 10 days.

         11. Willing to take study medication and to comply with all study procedures.

         12. In women of childbearing potential, negative pregnancy test and commitment to use
             contraceptive method throughout the study.

        