

          -  Patients with pulmonary fibrosis after standard treatment of COVID-19

          -  Age 18-65

          -  2019-nCoV nucleic acid negative in respiratory tract or blood samples were detected by
             real-time fluorescence PCR for more than 2 times

          -  The patient did not participant in other drug clinical studies within 1 month.

          -  The patient or the patient's guardian agrees to participate the trial and sign the
             informed Consent Form

        