

          -  It conforms to the diagnostic criteria of confirmed cases of COVID-19;

          -  Age from 18-75, regardless gender.

          -  The patient informed consent and sign the informed consent form (if the subject has no
             capacity, limited capacity and limited expression of personal will, he or she should
             obtain the consent of his guardian and sign the informed consent at the same time).

        