

          -  SARS-CoV-2 infection confirmed by real time-PCR and

          -  Positive imaging: consolidation, ground glass opacities, or bilateral pulmonary
             infiltration either by CT-scan or chest x-ray; and

          -  Need of oxygen therapy to maintain SO2>94% OR FiO2/PaO2 > 20 and at least two of the
             following laboratory measures:

          -  CRP level >70 mg/L

          -  CRP level >= 40 mg/L and doubled within 48 hours (without other confirmed infectious
             or non-infectious course),

          -  Lactatdehydrogenase > 250 U/L,

          -  thrombocytopenia < 120.000 x 10E9/L,

          -  lymphocyte count < 0.6 x 10E9/L,

          -  D-dimer > 1 ug/mL,

          -  serum ferritin > 300 ug/mL

        