

          -  SARS-CoV2 Infection diagnosed by rt-PCR

          -  CT-scan confirmed multifocal interstitial pneumonia

          -  Need of oxygen therapy to maintain SO2>93%

          -  Worsening of lung involvement, defined as (one of the following criteria):

               -  Worsening of oxygen saturation >3 percentage points or decrease in PaO2 >10%,
                  with stable FiO2 in the last 24h

               -  Need of increase FiO2 in order to maintain a stable SO2 or new onset need of
                  mechanical ventilation in the last 24h

               -  Increase in number and/or extension of pulmonary areas of consolidation

        