

          1. Admitted to a hospital with symptoms suggestive of COVID-19 infection.

          2. Subject (or legally authorized representative) provides written informed consent prior
             to initiation of any study procedures.

          3. Understands and agrees to comply with planned study procedures.

          4. Agrees to the collection of oropharyngeal (OP) swabs.

          5. Male or non-pregnant female adult > / = 18 years of age at time of enrollment.

          6. Has laboratory-confirmed SARS-CoV-2 infection as determined by polymerase chain
             reaction (PCR) or other commercial or public health assay in any specimen collected <
             72 hours prior to randomization.

             Note - 72 hours is not necessarily time from initial diagnosis. If > / = 72 hours
             since positive PCR, the PCR may be repeated to assess eligibility.

          7. Illness of any duration, and at least one of the following:

               -  Radiographic infiltrates by imaging (chest x-ray, CT scan, etc.), OR

               -  Clinical assessment (evidence of rales/crackles on exam) AND SpO2 < / = 94% on
                  room air, OR

               -  Requiring supplemental oxygen, OR

               -  Requiring mechanical ventilation.

          8. Women of childbearing potential must agree to either abstinence or use at least one
             primary form of contraception not including hormonal contraception from the time of
             screening through Day 29.

          9. Agrees to not participate in another clinical trial for the treatment of COVID-19 or
             SARS-CoV-2 through Day 29.

        