

          1. Laboratory confirmed COVID19 infection defined with a positive RT-PCR from any
             specimen and/or detection of SARS-CoV-2 IgM/IgG antibodies.

          2. Hospital admission with at least one of the following:

               1. fever >= 36.6 *C from axillary site; or >= 37.2*C from oral site; or >= 37.6*C from
                  tympanic or rectal site.

               2. Respiratory rate >= 24 bpm

               3. cough

          3. Spontaneous breathing with or without hypoxia of any degree. Gas exchange and
             ventilation maybe assisted by any continuous continuous airway pressure (CPAP), or any
             system of Non Invasive Ventilation (NIV), with Positive End-Expiratory Pressure (PEEP)
             <= 10 cmH2O.

        