

          -  Positive SARS-CoV-2 test and test results received within the previous three days

          -  Not currently hospitalized

          -  Willing and able to receive study drug by mail

          -  Willing and able to return internet-based study questionnaires at baseline and 14 days

          -  No known allergy or other contraindication to macrolides

          -  Age 18 years older at the time of enrollment

          -  Provision of informed consent

        