

        - Age:

        At least 18 years of age at the time of signing the ICF.

        - Type of Subject and Disease Characteristics:

        Documented or confirmed SARS-CoV-2 infection by PCR test nasopharyngeal swab <= 2 days
        before randomization.

        Hospitalized for COVID-19.

        Diagnosed with COVID-19 as defined by having at least 2 of the following signs or symptoms
        within the past 2 days:

        Fever defined as a body temperature of >= 38.0 *C oral, or >= 38.3 *C rectal, forehead or
        aural (axillary temperatures are not allowable);

        Cough;

        Fatigue;

        Shortness of breath.

        Radiographic evidence (chest x-ray or CT scan) of one the following:

        Ground-glass opacities, or

        Local or bilateral patchy infiltrates, or

        Interstitial pulmonary infiltrates.

        - Sex:

        Male and/or female subjects.

        Contraception use by men or women should be consistent with local regulations regarding the
        methods of contraception for those participating in clinical studies.

        All subjects (male or female) who are of childbearing potential must agree to use highly
        effective contraception during the study. Female subjects and male partners of female
        subjects must continue to use highly effective contraception for 30 days after the last
        dose of study drug. Female subjects should not donate oocytes during this time. Male
        subjects and female partners of male subjects must continue to use highly effective
        contraception for 90 days. Male subjects must agree not to donate sperm during this time.

        Note: Abstinence is acceptable if this is the usual lifestyle and preferred contraception
        for the subject.

        Note: Ethinyl estradiol is the primary estrogen used in hormonal contraceptives. The
        progestin component consists of norethindrone, levonorgestrel, norgestrel, norethindrone
        acetate, ethynodiol diacetate, norgestimate, desogestrel, and drospirenone. As BLD-2660 is
        a weak CYP3A4 inducer, exposure to both the estrogen and progestin components in hormonal
        contraceptives may be decreased, resulting in an increased risk of pregnancy. As such, it
        is recommended that subjects who are on hormonal contraceptives for birth control should
        use an alternate means of contraception (condoms, diaphragms, intrauterine device (IUD),
        other barrier methods, sexual abstinence, etc.) during participation in the study.

        Women of childbearing potential must have a negative serum pregnancy test at Screening
        within 72 hours prior to first administration of study drug.

        Women not of childbearing potential must be postmenopausal (defined as cessation of regular
        menstrual periods for at least 1 year

        - Informed Consent:

        Capable of giving signed informed consent which includes compliance with the requirements
        and restrictions listed in the ICF and in this protocol

        