

          1. Positive for RNA of SARS-CoV-2 from respiratory specimens or blood specimens

          2. Hypoxemic

          3. Severe COVID-19

          4. If female, subject must not be pregnant or nursing.

          5. Non-vasectomized males are required to practice effective birth control methods

          6. Capable of understanding and complying with procedures as outlined in the protocol as
             judged by the Investigator and able to sign informed consent form prior to the
             initiation of any screening or study-specific procedures.

        