

          -  Documented COVID-19 infection as evidenced by positive PCR (or comparable clinical
             assay) for SARS-CoV-2

          -  Less than 48 hours since time of hospital admission OR if hospital-acquired COVID-19
             is suspected, less than 48 hrs since onset of symptoms

          -  Adolescents and adults age >=16 years

          -  Subject or legally authorized representative able to give informed consent

          -  Admitted to hospital

        