
        1. Laboratory-confirmed SARS-CoV-2 infection as determined by PCR, or other commercial or
             public health assay in any specimen < 48 hours prior to randomization, and requiring
             hospital admission in the opinion of the attending physician.

          2. Provides written informed consent prior to initiation of any study procedures (or
             legally authorized representative).

          3. Understands and agrees to comply with planned study procedures.

          4. Agrees to the collection of OP swabs and venous blood per protocol.

          5. Male or female adult >=18 years of age at time of enrollment.
      