

          -  Completed Informed Consent

          -  Age >= 18 years old

          -  Individual is currently working with a trial participating site where individuals
             receive healthcare ("healthcare worker") or is associated with the site through
             emergency services

          -  Able to speak and read English or Spanish

          -  At risk for COVID-19 infection through one or more of the following work exposures:

               -  in the Intensive care unit, or

               -  in the Emergency department, or

               -  in Emergency Services, or

               -  in a COVID-19 hospital unit/ward, or

               -  in respiratory services

        