

          1. Aged 18-90 years

          2. The patient is likely to fulfill the ARDS criteria (Berlin definition) and need
             intubation, ventilator-assisted or ECMO-assisted treatment within 7 days of admission
             to hospital

          3. Suspected or verified COVID-19 infection

          4. At least one risk factor for increased mortality in COVID-19: currently published e.g.
             Smoking, Hypertension, Diabetes, Cardiovascular disease

          5. Documented informed consent according to ICH-GCP and national regulations

        