

          1. Age: 18-80 years old, male and female;

          2. Covid-19 confirmed cases;

          3. Comply with any of the following:

               -  Dyspnea, RR >= 30 times / min;

                    -  In resting state, transcutaneous oxygen saturation <= 93%;

                         -  Oxygenation index (PaO2 / FiO2) < 300MMHG;

          4. Pulmonary imaging showed diffuse exudative lesions.

        