:

        1. Adult patients admitted to an ICU for severe CAP within 48 hours of hospital admission
        with: i. symptoms or signs or both that are consistent with lower respiratory tract
        infection AND ii. Radiological evidence of new onset consolidation (in patients with
        pre-existing radiological changes, evidence of new infiltrate) 2. Requiring organ support
        with one or more of: i. Non-invasive ii. Invasive ventilatory support; iii. Receiving
        infusion of vasopressor or inotropes

        PLATFORM 