

          -  According to the risk stratification criteria of the Emilia-Romagna Region, Italy
             (accessed on March 24th, 2020 http://www...), eligible patients will belong to the
             Scenario 2, and 3a (slightly modified) as follows:

        Scenario 2 Positive nasopharyngeal swab for COVID-19, asymptomatic or paucisymptomatic,
        aged >=70 years and/or with clinical risk factors for poor outcome (clinically relevant
        chronic lung disease, diabetes and/or heart disease) or - symptomatic with respiratory or
        systemic symptoms, however clinically stable (MEWS<3) with CT imaging showing viral
        pneumonia and positive or pending pharyngo-nasal swab for COVID-19: Temperature 38*C and/or
        intensive cough, Respiratory rate < 25 /min, oxygen saturation (pulse oximetry) >95%

        Scenario 3 A

        Positive swab for COVID-19

        - with respiratory and/or systemic symptoms and initial mild respiratory failure e with
        objective signs of lung involvement; the patient is in stable conditions (MEWS < 3)
        Temperature>38*C and or intensive cough, Respiratory rate >=25 /min, or oxygen saturation
        94- 95% in room air

        