

          -  Patients with proven SARS-CoV-2 infection by an accepted assay with symptoms
             consistent with COVID-19

          -  Ability to measure and quantify viral load by quantitative PCR

          -  Temperature >100.6*F

          -  Age 18 to 89

          -  Ability to swallow oral medications

          -  Patients must read, understand and sign IRB approved informed consent

        