

          1. Males and females, at least 40 years of age, capable and willing to provide informed
             consent;

          2. Patient must have received a diagnosis of COVID-19 infection within the last 24 hours;

          3. Outpatient setting (not currently hospitalized or under immediate consideration for
             hospitalization);

          4. Patient must possess at least one of the following high-risk criteria: 70 years or
             more of age, diabetes mellitus, uncontrolled hypertension (systolic blood pressure
             >=150 mm Hg), known respiratory disease (including asthma or chronic obstructive
             pulmonary disease), known heart failure, known coronary disease, fever of >=38.4*C
             within the last 48 hours, dyspnea at the time of presentation, bicytopenia,
             pancytopenia, or the combination of high neutrophil count and low lymphocyte count;

          5. Female patient is either not of childbearing potential, defined as postmenopausal for
             at least 1 year or surgically sterile, or is of childbearing potential and practicing
             at least one method of contraception and preferably two complementary forms of
             contraception including a barrier method (e.g. male or female condoms, spermicides,
             sponges, foams, jellies, diaphragm, intrauterine device (IUD)) throughout the study
             and for 30 days after study completion;

          6. Patient must be able and willing to comply with the requirements of this study
             protocol.

        