

          1. Patients diagnosed as COVID-19:

               1. mild patient: fever,respiratory and other symptoms, the manifestation of
                  pneumonia can be seen on imaging.

               2. severe patients: meet the definition of severe pneumonia(comply with any of the
                  followings): Shortness of breath,RR>=30 bpm;In a resting
                  state:SPO2<=93%;PaO2/FiO2<=300mmHg.

          2. Age>=18 years old,unlimited gender.

          3. Patients who cannot stop the following drugs during the trial:erythromycin or strong
             inhibitors of CYP3A4 (such as saquinavir,ketoconazole,itraconazole),nonspecific
             inhibitors of CYP (such as cimetidine),HIV protease inhibitors (such as ritonavir).

          4. Willing to participate in this study,signed Informed Consent and willing to
             participate in regular follow-up during the study.

        