

          1. Age >=18 years at time of signing Informed Consent Form

          2. Laboratory (RT-PCR) confirmed infection with 2019-nCoV.

          3. Lung involvement confirmed with chest imaging

          4. Hospitalized with a SaO2/SPO2<=94% on room air or Pa02/Fi02 ratio <300mgHg

          5. <=12 days since illness onset

          6. Willingness of study participant to accept randomization to any assigned treatment
             arm.

          7. Must agree not to enroll in another study of an investigational agent prior to
             completion of Day 28 of study.

        