

          1. Female and male patients over the age of 18.

          2. Confirmed COVID-19 infection by PCR analysis.

          3. Hospitalized at Hasharon Medical Center.

          4. Display moderate to severe symptoms of respiratory infection.

          5. Willing and able to convey informed consent.

          6. Willing and able to comply with all study procedures

          7. Female patients of childbearing potential and male patients with partners of
             childbearing potential must agree to use adequate methods of contraception during the
             study and through 90 days after the last dose of study medication. Female patients of
             childbearing potential are all those except patients who are surgically sterile, who
             have medically documented ovarian failure, or who are at least 1 year postmenopausal.

        