

          -  Adult (age >= 18 years)

          -  Confirmed OR suspected COVID-19,

               -  Confirmed: Positive assay for COVID-19 within the last 10 days

               -  Suspected: Pending assay for COVID-19 WITH high clinical suspicion

          -  Scheduled for admission or already admitted to an inpatient bed

          -  Patients must be enrolled within 48 hours of hospital admission

        