

          -  Participants that, after receiving appropriate information on the study design,
             objectives, possible risks and acknowledging they have the right to withdraw from the
             study consent at any time, sing the informed consent for participation in the study.

          -  Male or female aged 18-65 years.

          -  Health care workers in public or private hospitals in Spain in areas of risk of
             SARS-CoV-2 transmission.

          -  No previous diagnosis of SARS-CoV-2 (COVID-19) infection plus no symptoms compatible
             with SARS-CoV-2 (COVID-19) since 1st of March 2020 until the date of enrolment in the
             study.

          -  Understanding of the aim of the study and, therefore, acknowledging they have not been
             on any drug aiming at pre exposure prophylaxis against SARS-CoV-2 (COVID-19) since 1st
             of March 2020. This also includes PrEP for HIV.

          -  Negative pregnancy test during the previous 7 days to start treatments or more than 2
             years after menopause.

          -  Women of reproductive age and their partners should commit to use and highly effective
             contraceptive method ( double barrier, hormonal contraception), during the study
             period and until 6 months after the last dose of treatment.

        