

          1. Clinically diagnosed with Corona Virus Disease 2019

          2. Increased interleukin-6

          3. Sign the informed consent

          4. Subjects who can take medicine orally

          5. Agree to collect clinical samples

          6. Female subjects of childbearing age are not pregnant and agree to take effective
             contraception within 7 days of the last oral medication to ensure that they are not
             pregnant within 3-6 months

          7. Male patients agree to effective contraception within 7 days of last oral medication.

        