for a case:

          1. Patients who meet the requirements of the New Coronavirus Infection Diagnosis (Acute
             respiratory infection symptoms or acute cough alone and positive PCR)

          2. Aged >=18 years male or female;

          3. In women of childbearing potential, negative pregnancy test and commitment to use
             contraceptive method throughout the study.

          4. Willing to take study medication

          5. Willing to comply with all study procedures, including repeat nasal swab at day 3

          6. Able to provide oral and written informed consent

        