

        Patients eligible for inclusion in this Treatment Plan have to meet all of the following
        criteria:

        Written patient informed consent or assent must be obtained prior to start of treatment.

          -  Patients aged >= 6 years

          -  Patients clinically diagnosed with SARS-CoV-2 infection, either through positive serum
             antibodies (IgM or IgG); or by PCR; or by other approved diagnostic methodology.
             Patients with presumptive diagnosis of COVID-19 (other respiratory causes ruled out
             and SARS-CoV-2 test pending) may be included.

          -  Adult and adolescent patients (>=12years), who meet one of the below criteria

               -  Respiratory frequency >= 30/min

               -  Oxygen saturation <= 93% on room air (FiO2=0.21)

               -  Arterial oxygen partial pressure (PaO2)/ fraction of inspired oxygen (FiO2)
                  <300mmHg(1mmHg=0.133kPa) (corrective formulation should be used for higher
                  altitude regions (over 1000m).

        AND

        -- Patients with lung imaging showing pulmonary infiltrates (chest X-ray or CT scan)

        Pediatric patients (>=6-<12 years) who meet one of the below criteria (where appropriate):

          -  Shortness of breath

          -  Oxygen saturation <92% on room air (Fi)2=0.21)

          -  Labored breathing (e.g. wheezing, flaring of nostrils, three concave sign), cyanosis,
             intermittent apnea.

          -  Lethargy or convulsions

          -  Refusal to eat or difficulty with feeding; signs of dehydration

        