

          1. CT image is characteristic of viral pneumonia;

          2. 2019-ncov infection (positive nucleic acid test) is confirmed by pathogenic test;

          3. In compliance with the 2019-nCoV infection severe pneumonia diagnosis standard
             (according to the novel coronavirus infection pneumonia diagnosis and treatment
             program (Trial Implementation Version 5) issued by the National Health and Medical
             Commission, and WHO 2019 new coronavirus guidelines standards). It is severe if it
             meets any of the following: (A) Increased breathing rate (>=30 beats / min), difficulty
             breathing, cyanosis of the lips; (B) When inhaling, means oxygen saturation <=93%; (C)
             Partial pressure of arterial oxygen (PaO2) / Fraction of inspired oxygen (FiO2) <=300
             mmHg (1mmHg = 0.133kPa);

          4. 18 years old <= age <= 65 years old, regardless of gender;

          5. The patient or legal donor agrees to participate in the study and signs the informed
             consent.

        