

          1. Age >= 18 years;

          2. Clinically diagnosed patients with new type of coronavirus pneumonia, including: in
             accordance with the criteria for suspected cases, have one of the following etiology
             evidence:

              Real-time fluorescence RT-PCR of respiratory specimens or blood specimens for
             detection of new coronavirus nucleic acid;

              Sequencing of viral genes in respiratory specimens or blood specimens, highly
             homologous to known new coronavirus

          3. The time interval between the onset of symptoms and random enrollment is within 7
             days. The onset of symptoms is mainly based on fever. If there is no fever, cough,
             diarrhea or other related symptoms can be used.

        