

          1. Confirmed SARS-CoV-2 infection, defined as RT-PCR provincial laboratory confirmation.

          2. Self-reported symptoms of SARS-CoV-2 infection including any of the following: fever
             >=37.5*C, cough, dyspnea, chest tightness, malaise, sore throat, myalgias, or coryza

          3. Time from a positive test result to day 1 of treatment <96 hours

          4. Time from patient reported first symptoms to day 1 of treatment <12 days

          5. Adults, age 18 and over, with any risk factor for severe disease

          6. Resident of Alberta or if not a resident of Alberta able to provide complete follow-up
             data

          7. Agrees to use adequate contraception for the duration of the study

          8. Informed consent

        