

          -  Male and female participants hospitalized due to severe respiratory syndrome with or
             without a confirmatory diagnosis of SARS-CoV-2

          -  aged over 18 years old

          -  provide written informed consent prior to the commencement of any study procedure

        meeting at least one the following criteria:

          -  age over 51 years OR

          -  pre-existing pulmonary disease OR

          -  decompensated chronic kidney impairment OR

          -  decompensated diabetes OR

          -  systemic arterial hypertension OR

          -  cardiovascular disease OR

          -  use of immunobiological drugs OR

          -  use of immunosuppressive drugs OR

          -  HIV/AIDS patients (CD4+ lymphocytes below 250) OR

          -  cancer.

        AND in addition to hospitalization, patients must present at least one of the following
        criteria:

          -  respiratory rate higher than 24 breathing incursions per minute OR

          -  heart rate higher than 125 beats per minute (in the absence of fever) OR

          -  peripheral oxygen saturation lower than 90% in ambient air OR

          -  shock (defined as mean arterial pressure less than 65 mmHg, requiring vasopressor or
             oliguria or lowering level of consciousness)

        