
          1. age >=60 years OR age 18-59 years with one of the following conditions:

               1. chronic lung disease

               2. chronic cardiovascular disease

               3. diabetes

               4. malignancy diagnosed within 5 years prior to enrollment

               5. chronic kidney disease

          2. SARS-CoV-2 infection confirmed in RT-PCR (nasopharyngeal swab)

          3. Hospitalization not required based on clinical judgement

          4. Ability to participate in telemedical care

        