

          -  1. Subjects must have a documented positive test for the COVID-19 virus within 72
             hours of the administration of study drug

          -  2. Subjects who have no requirement for oxygen (Ordinal Scale for Clinical Improvement
             score of 3 or less)

          -  3. Subjects must be under observation or admitted to a controlled facility or hospital
             (home quarantine is not sufficient)

          -  4. Subjects must be receiving standard of care (SOC) for COVID-19

          -  5. Subject's spirometry (forced expiratory volume in one second [FEV1] and forced
             vital capacity [FVC]) must be >=70% of predicted value

          -  6. If female, must be either post-menopausal (one year or greater without menses),
             surgically sterile, or, for female subjects of child-bearing potential who are capable
             of conception must be: practicing two effective methods of birth control (acceptable
             methods include intrauterine device, spermicide, barrier, male partner surgical
             sterilization, and hormonal contraception) during the study and through 30 days after
             completion of the study. Abstinence is not classified as an effective method of birth
             control.

          -  7. If female, must not be pregnant, plan to become pregnant, or nurse a child during
             the study and through 30 days after completion of the study. A pregnancy test must be
             negative at the Screening Visit, prior to dosing on Day 1.

          -  8. If male, must be surgically sterile or willing to practice two effective methods of
             birth control (acceptable methods include barrier, spermicide, or female partner
             surgical sterilization) during the study and through 30 days after completion of the
             study. Abstinence is not classified as an effective method of birth control.

          -  9. Must have the ability to understand and give informed consent.

        