

          1. Age >=18 years at time of signing Informed Consent Form;

          2. Those who meet the diagnosis of severe new coronavirus pneumonia with laboratory
             confirmed infection with CoVID-19;

          3. Lung involvement confirmed with chest imaging;

          4. Hospitalized with a Pa02/Fi02 ratio <=300mgHg;

          5. 40%> lymphocyte percentage >=5%;

          6. No difficulty swallowing oral medications.

        