

          1. Age >= 18 years old.

          2. Hospitalized patient (or documentation of a hospitalization plan if the patient is in
             an emergency department) with illness of more than 5 days of duration with evidence of
             pneumonia by chest radiography / tomography computed chest and meets at least one of
             the following requirements:

               1. Non-critical patient with pneumonia in radiological progression and / or

               2. Patient with progressive respiratory failure at the last 24-48 hours.

          3. Laboratory confirmed SARS-CoV-2 infection (by PCR) or other commercialized analysis or
             public health in any sample collected 4 days before the randomization or COVID-19
             criteria following the defined diagnostic criteria at that time in the center.

          4. Patient with a maximum O2 support of 35%

          5. Be willing and able to comply with the study related procedures / evaluations.

          6. Women of childbearing potential * should have a negative serum pregnancy test before
             enrollment in the study and must commit to using methods highly effective
             contraceptives (intrauterine device, bilateral tubal occlusion, vasectomized couple
             and sexual abstinence).

          7. Written informed consent. In case of inability of the patient to sign the informed
             consent, a verbal informed consent from the legal representative or family witness (or
             failing this, an impartial witness outside the investigator team) will be obtained by
             phone.

        When circumstances so allow, participants should sign the consent form. The confirmation of
        the verbal informed consent will be documented in a document as evidence that verbal
        consent has been obtained.

        