
          -  Adult (age >= 18 years)

          -  Admitted to the hospital of any participating center

          -  Confirmed SARS-CoV-2 infection with either: positive laboratory test for SARS-CoV-2* ;
             or positive CT thorax diagnostic for SARS-CoV-2 infection according to the prevailing
             criteria

          -  Randomization:

               -  Within 24 hours of confirmed in-hospital SARS-CoV-2 infection diagnosis OR

               -  within 24 hours of hospital admission in case of pre-hospital confirmed
                  SARS-CoV-2 infection.

                    -  In case there is a lack of laboratory tests for SARS-CoV-2 in the
                       participating center of the potentially eligible patient, a positive
                       laboratory test for SARS-CoV-2 will be no longer required. In that case, the
                       potentially eligible patient needs to meet the prevailing criteria for the
                       diagnosis of SARS-CoV-2 infection of that participating center, such as
                       typical abnormalities on pulmonary CT in the setting of high clinical
                       suspicion of SARS-CoV-2 infection.

        