

          -  Willing and able to provide written informed consent, or with a legal representative
             who can provide informed consent, or enrolled under International Conference on
             Harmonization (ICH) E6(R2) 4.8.15 emergency use provisions as deemed necessary by the
             investigator (participants >= 18 years of age)

          -  Hospitalized with confirmed SARS-CoV2 by polymerase chain reaction (PCR) or known
             contact of confirmed case with syndrome consistent with coronavirus disease (COVID-19)
             with PCR pending

          -  Requiring invasive mechanical ventilation (e.g., via endotracheal intubation or
             tracheostomy)

          -  Adequate renal function with estimated glomerular filtration rate (eGRF) >= 30 ml/min
             by local laboratory measure

          -  Alanine aminotransferase (ALT) <= 5 x upper limit of normal (ULN) by local laboratory
             measure

        