

          1. Signed informed consent

          2. negative pregnancy test in women

          3. COVID-19 confirmed by rtPCR in any respiratory sample.

          4. Severe COVID-19 disease defined as any from the following:

               1. Pulse oximetry less than 91% or a 3% drop from base pulse oximetry or need to
                  increase supplementary oxygen in chronic hypoxia

               2. Need for mechanical ventilation (invasive or non invasive )

               3. Sepsis/septic shock.

        