

          1. Subjects or their legal representatives have signed the informed consent form(ICF);
             agree not to participate in other clinical studies within 30 days after the last
             administration from the first administration of the study drug.

          2. Subjects are aged >= 18 and <= 75;

          3. Meet the diagnostic criteria for 2019-nCoV pneumonia (V5.0);

          4. SOFA score: 1 ~ 13 points.

          5. A retreated patient or the relapsed patient meets any of the following criteria:

               -  Have fever again or aggravated clinical symptoms;  2019nCOVRNA in the throat
                  swabs converts from negative to positive;  The clinical symptoms don't improve
                  or 2019nCOVRNA continues to be positive;  The chest CT shows pneumonia or
                  fibrosis progression.

        Clinical stratification:

          1. Mild type: clinical symptoms mild or asymptomatic, no pneumonia performance in CT, but
             positive 2019-nCoV in throat swabs or gargle.

          2. Ordinary type: fever, respiratory symptoms, etc., pneumonia performance visible in CT.

          3. Severe type: meeting any of the following criteria:

        (1) Respiratory distress, RR>=30 times/min; (2) Finger oxygen saturation <=93% in rest state;
        (3) Arterial partial pressure of oxygen (PaO2)/concentration of oxygen inhalation
        (FiO2)<=300mmHg (1mmHg=0.133kPa).

        4. Critical type: meeting any of the following criteria:(1)Respiratory failure occurs and
        mechanical ventilation is required;(2)Patients go into shock;(3)ICU is needed for other
        organ failure.

        