

          -  Adults aged 18-90

          -  Confirmed laboratory COVID-19 infection by RT-PCR

          -  Meeting severe or critical criteria of COVID-19 infection as defined at treating
             hospital

          -  Confirmed pneumonia by chest radiograph or computed tomography

          -  Fever defined as temperature >= 36.6 *C armpit, >= 37.2 *C oral, or >= 37.8 *C rectal

          -  Oxygen saturation less than 92%

        