

          -  Men and women aged 18 to 75 years (inclusive)

          -  In line with the new coronavirus infection pneumonia diagnosis and treatment plan
             (trial version 4) issued by the Health Commission, patients with new coronavirus (2019
             ncov) pneumonia were clinically diagnosed;

          -  The subjects must be able to understand the study and willing to participate in the
             study, and sign the informed consent (if the subjects with no behavioral ability think
             it is in their own interests to participate in the test, they should sign the informed
             consent by their legal guardian, or notify the consent by phone (recording) and
             explain it in the original medical record and other relevant documents).

        