

          -  Documented COVID19 pneumonia (positive SARS-CoV2 test, bilateral abnormalities/
             infiltrates on chest x-ray or computed tomography, active fever or documented fever
             within 24-48 or ongoing anti-pyretic use to suppress fever).

          -  Hypoxia (room air SpO2 <92% or requirement for supplemental oxygen).

          -  Increased serum inflammatory markers (CRP > 5 mg/dl AND LDH >upper limit of normal for
             local laboratory).

        