

          1. Adult SARI patients with 2019-ncov infection confirmed by PCR;

          2. Absolute value of lymphocytes < 0. 6x 109/L;

          3. Severe respiratory failure within 48 hours and requires admission to ICU. (severe
             respiratory failure was defined as PaO2/FiO2 < 200 mmHg and was supported by positive
             pressure mechanical ventilation (including non-invasive and invasive mechanical
             ventilation, PEEP>=5cmH2O))

        