

          1. Aged between 18 and 75 years, extremes included, male or female

          2. Patients diagnosed with mild or common type COVID-19, according to the official
             guideline "Pneumonia Diagnosis and Treatment Scheme for Novel Coronavirus Infection
             (Trial Version 6)"

          3. patients can generally tolerable for treatment recommended by the official guideline
             "Pneumonia Diagnosis and Treatment Scheme for Novel Coronavirus Infection (Trial
             Version 6)"

          4. Patients have not been accompanied by serious physical diseases of heart, lung, brain,
             etc.,Eastern Cooperative Oncology Group score standard:0-1

          5. Ability to understand and the willingness to sign a written informed consent document.

        