

          -  Participant is willing and able to give informed consent for participation in the
             study and agrees with the study and its conduct

          -  Agrees not to self-medicate with chloroquine, hydroxychloroquine or other potential
             antivirals

          -  Adults (exact age is dependent on countries)

          -  Not previously diagnosed with COVID-19

          -  Not currently symptomatic with an Acute Respiratory Infection

          -  Participant A. works in healthcare facility or other well characterised high-risk
             environment, OR B. is an inpatient or relative of a patient in a participating
             hospital and likely exposed to COVID-19 infection or another high-risk group

          -  Possesses an internet-enabled smartphone (Android or iOS)

        