

          1. High risk close contact with a confirmed COVID-19 case during their symptomatic
             period, including one day before symptom onset, within the past 1-7 days. High risk
             close contact is defined as any of the following exposures without the consistent
             appropriate use of recommended personal protective equipment:

               1. Provided direct care for the index case

               2. Had close physical contact with the index case

               3. Lived with the index case

               4. Had close contact (within 2 metres), without direct physical contact, for a
                  prolonged period of time

               5. Had direct contact with infectious body fluids, including oral secretions,
                  respiratory secretions, or stool.

          2. Successfully contacted by the study team within 24 hours of study team notification of
             the relevant index COVID-19 case. This time window is necessary because the efficacy
             of PEP may be dependent on the timing of its initiation, and because randomization of
             a ring cannot be delayed while awaiting response from contacts that cannot be rapidly
             reached.

          3. Age >=6 months, since the safety and pharmacokinetic profiles of LPV/r in pediatric
             patients below the age of 6 months have not been established.

          4. Ability to communicate with study staff in English

        