

          -  The participants were diagnosed as pneumonia caused by 2019-nCoV, according to the
             notice on printing and distributing the diagnosis and treatment plan of pneumonia with
             new coronavirus infection (trial version 4 or update version) made by National Health
             Commission of the People's Republic of China;

          -  Participants aged over 18;

          -  Written the informed consent.

        