

          -  Recent (<=2weeks prior to randomization) PCR(Polymerase Chain Reaction) -Confirmed
             COVID-19 infection

          -  Presence of acute hypoxic respiratory failure defined as (either or both)

               -  saturation below 93% on minimal 2 l/min O2

               -  PaO2/FiO2 below 300

          -  Admitted to specialized COVID-19 ward

          -  Age 18-80

          -  Male or Female

          -  Willing to provide informed consent

        