Fulfilling all the following criteria

          1. Aged between 18 and 60 years, male or female.

          2. Hospitalized participants with diagnosis of COVID 19 by Real Time - Polymerase Chain
             Reaction.

          3. Moderate cases according to the official guideline "Pneumonia Diagnosis and Treatment
             Scheme for Novel Coronavirus Infection (Trial Version 6)".

          4. Confusion, Urea, Respiratory rate, Blood pressure-65 (CURB-65) >= 2.

          5. Sequential Organ Failure Assessment score (SOFA) < 6.

          6. Ability to understand and the willingness to sign a written informed consent document.

        