

          -  Aged 18-75 years old;

          -  Pneumonia patients with new coronavirus infection were confirmed to be positive by
             RT-PCR and clinical manifestations. The diagnosis standard refers to the diagnosis and
             treatment plan for pneumonia with new coronavirus infection (Current Trial Version);

          -  Patients with newly diagnosed respiratory system discomfort who have been hospitalized
             (the diagnosis time of respiratory system discomfort shall not exceed 7 days);

          -  Women and their partners who have no planned pregnancy for nearly half a year and are
             willing to take effective contraceptive measures within 30 days from the first
             administration of the study drug to the last administration;

          -  Agree not to participate in other clinical research within 30 days from the first
             administration of the study drug to the last administration;

          -  Patients who voluntarily sign informed consent.

        