

          1. At the time of randomization, requires supplemental oxygen >=2 LPM due to hypoxemia.
             Hypoxemia can be defined by meeting at least one of the following criteria:

               -  SpO2 <92% on or off supplemental oxygen

               -  Respiratory failure necessitating mechanical or non-invasive ventilation (CPAP or
                  Bi-PAP)

               -  Written declaration from Investigator that subject is clinically hypoxemic and
                  removal of oxygen supplementation would not be considered clinically appropriate
                  for the purpose of measuring SpO2 while on room air

          2. Immunocompromised, as defined by one or more of the following:

               -  Received an autologous or allogeneic hematopoietic stem cell transplantation
                  (HSCT) at any time in the past

               -  Received a solid organ transplant at any time in the past

               -  Has been or is currently being treated with chemotherapy for hematologic
                  malignancies (e.g., leukemia, myeloma, lymphoma) and/or solid tumor malignancies
                  (e.g., lung, breast, brain cancer) at any time in the past

               -  Has an immunodeficiency due to congenital abnormality (only applicable to
                  subjects age < 18 years old) or pre-term birth (only applicable to subjects age <=
                  2 years old)

          3. Has, within 3 days prior to randomization, a confirmed LRTI with a sialic acid
             dependent respiratory virus

          4. If female, subject must meet one of the following conditions:

               -  Not be of childbearing potential or

               -  Be of childbearing potential and have a negative urine/serum pregnancy test and
                  agrees to practice an acceptable method of contraception

          5. Non-vasectomized males are required to practice effective birth control methods

          6. Capable of understanding and complying with procedures as outlined in the protocol

          7. Provides signed informed consent prior to the initiation of any screening or
             study-specific procedures

        For COVID-19 sub study:

          1. Be >=18 years of age

          2. Provide adequate medical history to permit accurate stratification (but health status
             may be healthy, high-risk conditions, or immunocompromised).

          3. Prior to SARS CoV 2 infection, has the ability to carry out self-care activities of
             daily living (basic ADL)

          4. Have lower respiratory tract infection (LRTI) confirmed by CT imaging, with or without
             contrast, to involve at least 2 lobes of the lung.

          5. Has laboratory-confirmation of the presence of SARS CoV 2 in the respiratory tract by
             at least one of the following samples

          6. Satisfy inclusion criteria #1, 4, 5, 6, 7 of the main study

        