

          1. Confirmed COVID-19, and the nucleic acid test of respiratory specimens such as sputum
             or nasopharyngeal swabs is negative twice after the treatment (sampling interval is at
             least 24 hours);

          2. Negative nucleic acid test of respiratory specimens such as sputum or nasopharyngeal
             swabs during screening visits;

          3. High-resolution CT of the lung (HRCT) indicates pulmonary fibrosis (thickness of
             lobular septum, honeycomb-like changes, with or without bronchial / pleural
             distraction);

          4. Voluntarily participate in research and sign informed consent.

        