

          -  The subject has to grant permission to enter into the study by signing and dating the
             informed consent form before completing any study-related procedure such as any
             assessment or evaluation not related to the normal medical care of the subject.

          -  Able to give written inform consent and retained one copy of the consent form

          -  Male or female subject, aged between 16 - 100 years old.

          -  Subject diagnosed to be COVID19

          -  Female subject in good health and sexually active was instructed by the investigator
             to avoid pregnancy during the study and to use condom or other contraceptive measure
             if necessary. The subject was required to have a negative urine pregnancy test before
             being eligible for the study. (At each of the subsequent visit, a urine pregnancy test
             was performed).

          -  Subject judged to be reliable for compliance for taking medication and capable of
             recording the effects of the medication and motivated in receiving benefits from the
             treatment.and compliance to quarantine procedure 7-14 days after treatment

        