

          -  Household contact of index case: currently residing in the same household as an
             individual evaluated at NYP via outpatient, emergency department (ED), or inpatient
             services who (1) test positive for COVID-19, or (2) are defined as suspected cases, or
             persons under investigations (PUI), by the treating physician.

          -  Willing to take study drug as directed for 5 days.

        