

        I1. Age 18 or older at the time of enrolment. I2. Histologically or cytologically confirmed
        diagnosis of advanced or metastatic hematological or solid tumor (hematological or solid
        tumor, any type and any localization).

        I3. Documented diagnosis of COVID-19 (diagnostic test performed in a certified laboratory)
        or symptoms of COVID-19 associated with radiological signs of pneumonia as described by Shi
        et al.; I4. Cohort 2: patients with pneumonia confirmed by chest imaging, and an oxygen
        saturation (Sao2) of 94% or less while they are breathing ambient air or a ratio of the
        partial pressure of oxygen (Pao2) to the fraction of inspired oxygen (Fio2) (Pao2:Fio2) at
        or below 300 mg Hg.

        I5. Patient not eligible for a transfer to Resuscitation Unit (either due to underlying
        medical condition - including cancer - or due to lack of available bed).

        I6. Life-expectancy longer than 3 months.

        I7. Adequate bone marrow and end-organ function defined by the following laboratory
        results:

          -  Bone marrow:

               -  Hemoglobin >= 7.0 g/dL,

               -  Absolute Neutrophils Count (ANC) >= 1.0 Gi/L,

               -  Platelets >= 100 Gi/L;

          -  Hepatic function:

               -  Total serum bilirubin <= 1.5 x ULN (except patients with Gilbert's syndrome who
                  must have total serum bilirubin <= 3.0 x ULN),

               -  AST and ALT <= 5 ULN

          -  Renal function:

               -  Serum creatinine <= 2.0 x ULN or Cr. Cl. >= 30ml/min/1.73m (MDRD or CKD-EPI
                  formula); I8. Willingness and ability to comply with the study requirements; I9.
                  Signed and dated informed consent indicating that the patient has been informed
                  of all the aspects of the trial prior to enrolment (in case of emergency
                  situation, please refer to protocol section 13.1 PATIENT INFORMATION AND INFORMED
                  CONSENT); I10. Women of childbearing potential (Appendix 2) are required to have
                  a negative serum pregnancy test within 72 hours prior to study treatment start. A
                  positive urine test must be confirmed by a serum pregnancy test; I11. Women of
                  childbearing potential and male patients must agree to use adequate highly
                  effective contraception (Appendix 2) for the duration of study participation and
                  up to 6 months following completion of therapy; I12. Patient must be covered by a
                  medical insurance.

        