

          -  Documented COVID-19 pneumonia: defined as upper respiratory tract specimen
             (nasopharyngeal swab (NPS) or viral throat swab) positive for COVID-19 and/or imaging
             at computed tomography scan suggestive of COVID-19 pneumonia

          -  Oxygen saturation (SaO2) of 92% or less without oxygen support, or reduction of 3%
             from basal value of SaO2, or a ratio of the partial pressure of oxygen (PaO2) to the
             fraction of inspired oxygen (FiO2) (PaO2/FiO2) below 300.

          -  Any gender

          -  Age >= 18 years

          -  Written informed consent or as per Ethical Committee indication in case of patients
             not able to express written informed consent

        