

          1. Informed consent from patient or legal representative.

          2. Male or female, aged >= 18 years;

          3. Laboratory confirmation of 2019-nCoV infection by reverse-transcription polymerase
             chain reaction (RT-PCR) from any diagnostic sampling source;

          4. At least one of the characteristic symptoms of COVID-19

          5. Hospitalized for up to 36h with non-invasive ventilation or up to 24h with invasive
             ventilation.

          6. Negative result for pregnancy test (if applicable).

        