

          -  Adult >=18 years of age at time of enrolment.

          -  Has laboratory-confirmed SARS-CoV-2 infection as determined by PCR, or other
             commercial or public health assay in any specimen < 72 hours prior to randomization.

          -  Hospitalized patients with illness of any duration, and at least one of the following:

               -  Clinical assessment (evidence of rales/crackles on exam) AND SpO2 <= 94% on room
                  air, OR

               -  Acute respiratory failure requiring mechanical ventilation and/or supplemental
                  oxygen.

          -  Women of childbearing potential must agree to use contraception for the duration of
             the study. Acceptable birth methods control are listed in section 7.3

        