

          -  Must have positive nasopharyngeal swab for SARS-CoV-2 diagnosed via outpatient testing
             within the previous 48 hours

          -  Age >= 45 years

          -  Not hospitalized at the time of enrollment

          -  Established care with Providence provider

          -  Ability to understand a written or electronic informed consent document

          -  Reliable access to a computer or smartphone that can facilitate study communications
             via remote messaging or telephone and willingness to provide daily verbal check ins

        