

          1. Patients who meet the requirements of the New Coronavirus Infection Diagnosis (Acute
             respiratory infection symptoms or acute cough alone and positive PCR)

          2. Aged >=18 and < 75 years male or female;

          3. In women of childbearing potential, negative pregnancy test and commitment to use
             contraceptive method throughout the study.

          4. Willing to take study medication

          5. Willing to comply with all study procedures,

          6. Diagnosis of IBD disease, rheumatoid arthritis, seronegative spondyloarthritis or
             psoriasis for more than 6 months.

          7. Be on stable treatment with biological agents, for a minimum period of 6 months,
             including treatment with Infliximab, etanercept, adalimumab, certolizumab, golimumab,
             rituximab, abatacept, tocilizumab, sarilumab, secukinumab, vedolizumab, natalizumab,
             ustekinumab, tofacit

          8. Able to provide oral and written informed consent

        