

          1. Laboratory diagnosis:

               -  Respiratory specimen is positive for SARS-CoV-2 nucleic acid by RT-PCR; OR,

               -  The viral gene sequencing of the respiratory specimen is highly homologous to
                  known novel coronavirus.

          2. Fever:

             Axillary temperature >37.3*C

          3. Respiratory variables (meets one of the following criteria):

               -  Respiratory rate: RR >=25 breaths/min

               -  Oxygen saturation <=93% at rest on room air

               -  PaO2/FiO2 <=300 mmHg1 mmHg=0.133 KPa

               -  Pulmonary imaging showed that the lesions progressed more than 50% within 24-48
                  hours, and the patients were managed as severe

          4. HBsAg negative, or HBV DNA <=10^4 copy/ml if HBsAg positive; anti-HCV negative; HIV
             negative two weeks prior to signed Informed Consent Form (ICF)

          5. Appropriate ethics approval and

          6. ICF

        