

          -  age 18 years or older;

          -  positive reverse-transcriptase-polymerase-chain-reaction (RT-PCR) assay for COVID-19
             in a respiratory tract sample;

          -  intubated and mechanically ventilated;

          -  acute onset of ARDS, as defined by Berlin criteria as moderate-to-severe ARDS,3 which
             includes: (i) having pneumonia or worsening respiratory symptoms, (ii) bilateral
             pulmonary infiltrates on chest imaging (x-ray or CT scan), (iii) absence of left
             atrial hypertension, pulmonary capillary wedge pressure <18 mmHg, or no clinical signs
             of left heart failure, and (iv) hypoxemia, as defined by a PaO2/FiO2 ratio of <=200
             mmHg on positive end-expiratory pressure (PEEP) of >=5 cmH2O, regardless of FiO2.

        