

          -  18 years or older

          -  Moderate to severe COVID-19 associated disease as defined by the WHO

          -  Hospitalized patient

          -  Willing and able to provide written informed consent prior to performing study
             procedures

          -  Has laboratory-confirmed SARS-CoV-2 infection as determined by PCR, or other
             commercial or public health assay

          -  Illness of any duration, and at least one of the following: Radiographic infiltrates
             by imaging (chest x-ray, CT scan, etc.), or Clinical assessment (evidence of
             rales/crackles on exam) AND SpO2 <= 94% on room air, or Require mechanical ventilation
             and/or supplemental oxygen.

          -  Febrile defined as temperature >= 36.6 *C armpit, >= 37.2 *C oral, or >= 37.8 *C rectal
             documented within 48 hours of consent

        