

          -  Infection with COVID-19 diagnosed by positive RT-PCR SARS-CoV-2 or, if not performed,
             by thorax CT-scan suggesting viral pneumonia of peripheral predominance in a
             clinically significant context.

          -  Diagnosed within the previous 48 hours.

          -  Having at least one of the following two risk factors for complications:

          -  age >=75 years old

          -  Peripheral oxygen saturation (SpO2) <= 94% while breathing ambient air, or a partial
             oxygen pressure (PaO2) to fraction of inspired oxygen (FiO2) ratio <= 300 mmHg.

          -  Patients affiliated with or benefitting from a social security scheme

          -  Written and signed consent of the patient or a relative or, if not possible, emergency
             inclusion procedure

          -  Electrocardiogram showing absence of QT prolongation greater than 440 ms in men and
             460 ms in women.

        