

          -  1. Subjects must have documented exposure to COVID-19 and have a documented negative
             test for the virus within 72 hours of the administration of study drug

          -  2. Subjects must be free of clinical symptoms (fever, cough, shortness of breath) of a
             potential COVID-19 infection

          -  3. Subjects must be under quarantine in a controlled facility or hospital (home
             quarantine is not sufficient)

          -  4. Spirometry (forced expiratory volume in one second [FEV1] and forced vital capacity
             [FVC]) >=70% of predicted value

          -  5. If female, must be either post-menopausal (one year or greater without menses),
             surgically sterile, or, for female subjects of child-bearing potential who are capable
             of conception must be: practicing two effective methods of birth control (acceptable
             methods include intrauterine device, spermicide, barrier, male partner surgical
             sterilization, and hormonal contraception) during the study and through 30 days after
             completion of the study. Abstinence is not classified as an effective method of birth
             control.

          -  6. If female, must not be pregnant, plan to become pregnant, or nurse a child during
             the study and through 30 days after completion of the study. A pregnancy test must be
             negative at the Screening Visit, prior to dosing on Day 1.

          -  7. If male, must be surgically sterile or willing to practice two effective methods of
             birth control (acceptable methods include barrier, spermicide, or female partner
             surgical sterilization) during the study and through 30 days after completion of the
             study. Abstinence is not classified as an effective method of birth control.

          -  8. Ability to understand and give informed consent.

        