(case definition)

          -  Consented adults (age >=18 years)

          -  COVID-19 suspicious and

          -  Admitted to hospital or already in hospital and

          -  Fever (with or without at the time of randomization) and

          -  SARS (severe acute respiratory syndrome)

               -  shortness of breath (dyspnea) or

               -  image of typical or atypical pneumonia or

               -  oxygen desaturation (SpO2 <= 93)

        