

          1. Age >= 18 years and <= 64 years at the time of the assessment

          2. Able and willing to understand the study, adhere to all study procedures, and provide
             written informed consent

          3. Initial diagnosis of COVID-19 disease as defined by a FDA-cleared molecular diagnostic
             assay positive for SARS-CoV-2

          4. Display symptoms of COVID respiratory infection without respiratory distress

        