

          -  A contact person from confirmed case of SARS-CoV-2 infection

          -  Medical staff exposed from confirmed case of SARS-CoV-2 infection in hospitals

          -  Persons exposed to SARS-CoV-2 in COVID-19 outbreak situation with certain workplaces,
             religious groups, and military, etc.

               -  Subjects of study include both symptomatic and asymptomatic contacts.

        