

          1. Recruited subjects include all adult patients >=18 years hospitalised for virologically
             confirmed 2019-n-CoV infection.

          2. NEWS of >=1 upon recruitment

          3. Auditory temperature >=38*C with at least one of the following symptoms (cough, sputum
             production, sore-throat, nasal discharge, myalgia, headache or fatigue) upon admission

          4. Symptom duration <=10 days

          5. All subjects give written informed consent.

          6. Subjects must be available to complete the study and comply with study procedures.
             Willingness to allow for serum samples to be stored beyond the study period, for
             potential additional future testing to better characterize immune response.

        