

          -  All consecutive patients with mild to moderate COVID-19 infection

          -  Age >18 years,

          -  Clinical diagnosis of COVID19 infection

          -  Patients should present fever, cough and myalgia and weakness and radiological
             findings of pneumonia.

          -  All patients should be willing and able to provide written informed consent prior to
             performing study procedures.

        