

          1. Signed informed consent, demonstrating that the subject understands the procedures
             required for the study and the purpose of the study

          2. Healthy male or female subjects 18 years of age or older that are considered to be
             high-risk individuals. High-risk individuals are defined as all health care workers in
             hospitals, clinics, and emergency rooms, and medical facilities.

          3. Subjects must agree to practice at least one highly effective method of birth control
             for the duration of the study

        