

          -  Men or women 18 to 80 years of age inclusive, at the time of signing the informed
             consent

          -  Willing and able to provide informed consent

          -  Had a close contact of a person (index) with known PCR-confirmed SARS-CoV-2 infection
             or who is currently being assessed for COVID-19. Close contact defined as:

               1. Household contact (i.e., residing with the index case in the 14 days prior to
                  index diagnosis)

               2. Medical staff, first responders, or other care persons who cared for the index
                  case without personal protection (mask and gloves)

          -  Less than 4 days since last exposure (close contact with a person with SARS-CoV-2
             infection) to the index case

          -  Body weight < 100 kg (self-reported)

          -  Access to device and internet for Telehealth visits

        