

          -  Age >= 18 years old (Sub-studies 2 and 3)

          -  Competent and capable to provide informed consent

          -  Have access to a smart device such as a cell phone, tablet, laptop computer with
             necessary data/internet accessibility

          -  Subjects meeting the following criteria by Sub-Study

        Sub-Study 1:

          -  Age >=40 years since the risk of prolonged disease that progresses to severe COVID-19
             disease increases with age.

          -  PCR-positive for the SARS-CoV2 virus

          -  (Fever, and cough, or Fever and shortness of breath,

          -  <=4 days since the first symptoms of COVID-19 and date of testing

          -  Not taking azithromycin

          -  Not requiring hospitalization and is sent home for quarantine.

          -  Must live within 30 miles of HUP or Penn Presbytarian Medical Center to facilitate
             drop-off of medication

          -  Must own a working computer, or smartphone and have internet access

          -  Must be willing to fill out a daily symptom diary

          -  Must be available for a daily phone call,

          -  Must take their own temperature twice a day

          -  Must be willing to report the observed symptoms and development of COVID-19 in the
             co-inhabitants of the residence at which the quarantine will be served.

        Sub-Study 2 Hospitalized non-ICU service patients.

          -  PCR-positive for SARS-CoV-2

          -  Patients admitted to a floor bed at Hospital of the University of Pennsylvania or Penn
             Presbyterian.

          -  One or more of the following risk factors for progression to severe disease including:
             immunocompromising conditions, structural lung disease, hypertension, coronary artery
             disease, diabetes, age > 60, ferritin > 850, CRP > 6, D-dimer > 1000 Sub-Study 3
             Health Care Worker Prevention

          -  Emergency Medicine or Infectious Disease Team physician or nurse at HUP or PPMC

          -  >=20 hours per week of clinical work scheduled in the coming 2 months during the
             COVID-19 pandemic

          -  No fever, cough, or shortness of breath in the past 2 weeks

          -  Willing to report compliance with HCQ in the form of a diary

          -  Patients must be able to swallow and retain oral medication and must not have any
             clinically significant gastrointestinal abnormalities that may alter absorption such
             as malabsorption syndrome or major resection of the stomach or bowels.

        