

          1. Age 18 to 80.

          2. Confirmed COVID-19 diagnosis(including the clinically confirmed cases in Hubei).

          3. Accord with any of the following:  Respiratory distress, RR >= 30 breaths/min;  SpO2
             <= 93% at rest;  Partial arterial oxygen pressure (PaO2) / Fraction of inspiration O2
             (FiO2) <= 300mmHg (1mmHg = 0.133kPa).

          4. Chest imaging confirms lung involvement and has inflammatory exudation or pleural
             effusion.

        