

          -  Adult aged >=18years old;

          -  Laboratory (RT-PCR) confirmed 2019-nCoV infection in throat swab and/or sputum and/or
             lower respiratory tract samples;

          -  The interval between the onset of symptoms and randomized is within 7 days. The onset
             of symptoms is mainly based on fever. If there is no fever, cough or other related
             symptoms can be used;

          -  Meet any of the following criteria for severe or critical ill conditions:

               1. Respiratory rate >=30/min; or

               2. Rest SPO2<=90%; or

               3. PaO2/FiO2<=300mmHg; or

               4. Respiratory failure and needs mechanical ventilation; or

               5. Shock occurs; or

               6. Multiple organ failure and needs ICU monitoring;

          -  Sign the Informed Consent Form on a voluntary basis.

        