

          -  Judged to be healthy by the Investigator on the basis of medical history, physical
             examination and vital signs performed at screening.

          -  Able and willing to comply with all study procedures.

          -  Screening laboratory results within normal limits or deemed not clinically significant
             by the Investigator.

          -  Negative serological tests for Hepatitis B surface antigen (HBsAg), Hepatitis C
             antibody and Human Immunodeficiency Virus (HIV) antibody screening.

          -  Screening electrocardiogram (ECG) deemed by the Investigator as having no clinically
             significant findings (e.g. Wolff-Parkinson-White syndrome).

          -  Use of medically effective contraception with a failure rate of < 1% per year when
             used consistently and correctly from screening until 3 months following last dose, be
             post-menopausal, be surgically sterile or have a partner who is sterile.

        