

          1. Male or female, aged 18 to 80 years.

          2. Provided informed consent prior to any study specific procedure being conducted.

          3. Virological or serological diagnosis of SARS-CoV-2.

          4. Evidence of viral pneumonia (either CT scan or Chest Ultrasonogram).

          5. Oxygen saturation at rest in ambient air <= 95%.

          6. PaO2/FiO2 <300mmHg without oxygen inhalation

          7. Fever defined as temperature >= 36.6*C armpit, >= 37.2*C oral, >= 37.8*C rectal.

        