

          -  Adult healthcare workers (HCWs) (physicians, nurses, assistant nurses, dentists,
             physiotherapists, and midwives)

          -  HCW involved at the time of enrolment in the care of patients with confirmed or
             suspected SARS-CoV-2 infection in hospital settings, in outpatient care settings or in
             geriatric long-term care facilities

          -  HCW tested negative for HIV

          -  HCW affiliated to the French health insurance system

          -  HCW women of childbearing age with an effective contraception
             (ethinylestradiol-containing contraceptive pills are not regarded as effective in the
             context of LPV/r treatment)

          -  Willing to comply to study design and the follow-up

        