

          1. Age >=18 years;

          2. The laboratory (RT-PCR) confirmed the diagnosis of severe patients infected with
             CoVID-19 (refer to the fifth edition of the Chinese diagnosis and treatment guideline
             for trial); the diagnosis of new coronavirus pneumonia was confirmed, and any of the
             following: 1) Respiratory distress, breathing >=30 beats / min; 2) In the resting
             state, the oxygen saturation is <=93%; 3) Arterial blood oxygen partial pressure /
             oxygen concentration <=300mmHg

          3. The diagnosis is less than or equal to 12 days;

        