

          1. Age >=18 years

          2. Currently hospitalized or in an emergency department with anticipated hospitalization.

          3. Symptoms of acute respiratory infection, defined as one or more of the following:

               1. cough

               2. fever (> 37.5* C / 99.5* F)

               3. shortness of breath

               4. sore throat

          4. Laboratory-confirmed SARS-CoV-2 infection within the past 10 days or SARS-CoV-2
             laboratory test result pending plus a high clinical suspicion for COVID-19 as
             indicated by fulfilling all of the following:

               1. Cough with duration <=10 days

               2. Bilateral pulmonary infiltrates on chest imaging (radiograph, or computed
                  tomography or ultrasound) or new hypoxemia defined as SpO2 <=94% on room air

               3. No alternative explanation for symptoms of acute respiratory infection

        