

          1. Signed informed consent, demonstrating that the subject understands the procedures
             required for the study and the purpose of the study

          2. Healthy male or female subjects 18 years of age to 55 years of age

          3. Subjects must agree to practice at least one highly effective method of birth control
             for the duration of the study

          4. Diagnosis of COVID-19 by RT-PCR

        