
        Inclusion criera :

          -  Patient >= 18 years old and <= 75 years old

          -  Laboratory proved infection by COVID-19 within 2 days

          -  Hospitalization is required (based on investigator judgement)

          -  Patient affiliated to a social security regime

          -  Patient able to give free, informed and written consent

        Exclusion criteria :

          -  Oxygen flow rate >8l/min at inclusion

          -  Current treatment with any inhaled steroid (any other form of steroid administration
             does not exclude the patient)

          -  Intensive care unit is required for the patient (based on investigator judgement)

          -  Patient with cognitive impairment which do not guarantee proper use of the treatment
             by the patient himself

          -  Pregnant or breastfeeding women

          -  Participation in another interventional drug study involving human participants and
             concerning COVID-19 infection or being in the exclusion period of a previous study
             involving human participants

          -  Contraindications to the treatments (history of hypersensitivity)
      