

          1. Male or female patients aged 18 years and above;

          2. Hospitalised;

          3. Confirmed or suspected SARS-CoV-2 infection;

          4. National Early Warning Score (NEWS2) greater than or equal to 3 in a single parameter
             or NEWS2 > 5 overall;

          5. Acute hypoxemic respiratory failure: PaO2/FiO2 ratio less than or equal to 300 OR
             SpO2/FiO2 ratio < 315 (Kigali Modification)

          6. Provision of written informed consent by the patient OR by the patient's Legal
             Representative OR professional consultee.

        