

          -  Laboratory-confirmed SARS-CoV-2 infection as determined by polymerase chain reaction
             (PCR), result from any specimen (or other commercial or public health assay) within 2
             weeks prior to randomization and no alternative explanation for current clinical
             condition

          -  Hospitalized with illness of any duration with evidence of pneumonia and severe
             disease, critical disease, multi-system organ dysfunction or immunocompromised at
             baseline

          -  Ability to provide informed consent signed by study patient or legally acceptable
             representative

          -  Willingness and ability to comply with study-related procedures/assessments

        Key 