

        - A healthcare worker at high risk for COVID-19 exposure (defined below):

          -  Persons primarily working in emergency departments (physicians, nurses, ancillary
             staff, triage personnel)

          -  Persons primarily working in intensive care units (physicians, nurses, ancillary
             staff, respiratory therapists)

          -  Persons performing aerosol generating procedures (i.e. anesthesiologists, nurse
             anesthetists (CRNAs)

          -  First responders (i.e. EMTs, paramedics)

        