

          -  Subject (or authorized legal representative) who can provide written informed consent
             before beginning any study procedure.

          -  Understand and agree to abide by the study procedures.

          -  Adult #18 years of age at the time of inclusion in the study.

          -  Confirmation of SARS-CoV-2 infection by a microbiological test performed before
             randomization, no longer than 72 hours.

          -  Severity 3-4 according to the WHO 7-point ordinal scale.

        