

          -  Willing and able to provide written informed consent prior to performing study
             procedures

          -  Severe Acute Respiratory Syndrome Coronavirus (SARS-CoV)-2 infection confirmed by
             polymerase chain reaction (PCR) test <= 4 days before randomization

          -  Currently hospitalized with fever defined as temperature >= 36.6 *C armpit, >= 37.2 *C
             oral, or >= 37.8 *C rectal

          -  Peripheral capillary oxygen saturation (SpO2) > 94% on room air at screening

          -  Radiographic evidence of pulmonary infiltrates

        Key 