

          1. Adult male or female patients aged 18-85 years old;

          2. The newly diagnosed COVID-19 patients who meet the diagnostic criteria set forth in
             the "Guidance of Diagnosis and Treatment for Patients with Coronavirus Disease 2019
             (COVID-19) (Procedural Version 5 Amendment)", issued by the National Health Commission
             of the People's Republic of China on 8 February 2020;

          3. Patients whose blood oxygen saturation is not less than 90%.

          4. Patients who agree to participate in the study and voluntarily comply with the
             relevant requirements of the study.

        