

          1. Age >=18 years at time of signing Informed Consent Form

          2. Laboratory (RT-PCR) confirmed infection with 2019-nCoV.

          3. Lung involvement confirmed with chest imaging

          4. Hospitalised with:

               -  Fever - >=36.7*C -axilla or Oral temperature >= 38.0 *C or >=38.6*C tympanic or rectal
                  or

               -  And at least one of Respiratory rate >24/min Or Cough

          5. <=8 days since illness onset

          6. Willingness of study participant to accept randomization to any assigned treatment
             arm.

          7. Must agree not to enroll in another study of an investigational agent prior to
             completion of Day 28 of study.

        