

          1. Aged between 18 and 70 years, extremes included, male or female

          2. Fever (armpit temperature >=37.3 * C, or mouth temperature >=38.0 * C, or anal or ear
             temperature >=38.6 * C) <=7 days according to the official guideline "Pneumonia
             Diagnosis and Treatment Scheme for Novel Coronavirus Infection (Trial Version 5)"

          3. Laboratory test (RT-PCR) confirms infection 2019-nCoV

          4. No previous or experimental treatment for pneumonia associated with a novel
             coronavirus infection. Patients who have been treated with proprietary Chinese
             medicines or lopinavir / ritonavir tablets for less than 3 days can be enrolled

          5. Informed Consent Form (ICF) signed voluntarily

          6. Based on the investigator's judgment, the subject / legal guardian is considered
             reliable and able to comply with this program, visit plan and medication arrangement

        