

          -  Must have confirmed and documented Coronaviral (COVID-19) infection history with
             involvement of lung tissues

          -  Must be clear of any viral shed residual confirmed by negative viral testing protocol
             accepted by the Center for Disease Control (CDC) and/or the FDA

          -  Must have discharge confirmation from infectious disease managing Provider declaring
             freedom of viral load or active infection

          -  Must have a written Medical History of Physical and discharge summary (if
             hospitalized) from appropriate Center or Licensed Medical Provider

          -  Must agree to provide a HRCT LUNG study done at baseline (before), 3 months and 6
             months

          -  Must be able to provide full Informed Consent (ICF)

        