Fulfilling all the following criteria

          1. Aged between 18 and 60 years, male or female.

          2. Hospitalized participants with diagnosis for COVID 19 by Real Time - Polymerase Chain
             Reaction.

          3. Without treatment.

          4. Moderate cases according to the official guideline "Pneumonia Diagnosis and Treatment
             Scheme for Novel Coronavirus Infection (Trial Version 6)".

          5. Confusion, Urea, Respiratory rate, Blood pressure-65 (CURB-65) >= 2.

          6. Sequential Organ Failure Assessment score (SOFA) < 6.

          7. Ability to understand and the willingness to sign a written informed consent document.

        